### ISSUE TITLE
Get rid of a notice when browsing a group tag, sql errors

### ISSUE THREAD

**Issue by itdahde** [imath/bp-groups-taxo#12]
I got two sql errors when i try to view a tag

WP v4.6.1
BP v1.0.0-beta4

WordPress-Database-Error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN wp_term_relationships, wp_bp_groups g WHERE g.id = gm1.group_id AND' at line 1]
`SELECT DISTINCT g.id, g.*, gm1.meta_value AS total_member_count, gm2.meta_value AS last_activity FROM wp_bp_groups_groupmeta gm1, wp_bp_groups_groupmeta gm2, LEFT JOIN wp_term_relationships, wp_bp_groups g WHERE g.id = gm1.group_id AND g.id = gm2.group_id AND gm2.meta_key = 'last_activity' AND gm1.meta_key = 'total_member_count' AND g.id = wp_term_relationships.object_id AND ( wp_term_relationships.term_taxonomy_id IN (32) ) ORDER BY last_activity DESC LIMIT 0, 20`

By test i found out, there's a "," between the FROM , LEFT JOIN arguments and LEFT JOIN missing an expression.
I tested and let the "," stay and removed LEFT JOIN, then it works, but i do not know, where to change to get it work.

WordPress-Database-Error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN wp_term_relationships WHERE g.id = gm.group_id AND gm.meta_key = 'last' at line 1]
`SELECT COUNT(DISTINCT g.id) FROM wp_bp_groups g, wp_bp_groups_groupmeta gm, LEFT JOIN wp_term_relationships WHERE g.id = gm.group_id AND gm.meta_key = 'last_activity' AND g.id = wp_term_relationships.object_id AND ( wp_term_relationships.term_taxonomy_id IN (32) )`

Here was the same, hope to get it done

With best regardss from Germany, 

Alex

**Comment by imath** [comment]
i think i've fixed it in one of the branch, but forgot to upgrade master once 4.6 was released, thanks for your feedback, i'll look at it more carefully soon.

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
Could you check it's fixed in this branch https://github.com/imath/bp-groups-taxo/tree/beta-5 ?

**Comment by itdahde** [comment]
Hi imath, 

i testet that branch and all seems to be working, also the tag link query works correct. I thank you for your professional support and communication to that issue.

Have a nice day and with best Regards from Germany, Alex

**Comment by imath** [comment]
Great!

Thanks for your feedback i'll merge it with master asap.

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
Just merged beta-5 with master as it's fixing the issue.
