### ISSUE TITLE
bp 2.7

### ISSUE THREAD

**Issue by valuser** [imath/bp-groups-taxo#14]
just testing  - NOT in any way urgent.

 bp-groups-taxo version 1.0.0-beta5 with WP 4.6.1, TwentySixteen, and BuddyPress 2.7 rc2 

just have one have **one group type** in functions.php (exactly as per code lines 1-16 in https://codex.buddypress.org/developer/group-types/)

The following error comes up:

Warning: array_merge(): Argument #1 is not an array in /Users/valentinecosgrave/Documents/newwebsites/xample.dev/wp-content/plugins/bp-groups-taxo-master/bp-groups/bp-groups-tag.php on line 242

All good though with BuddyPress 2.6

Cheers and thanks!

**Comment by imath** [comment]
Thanks for your feedback @valuser could you check branch beta-6 is fixing the issue ?

> https://github.com/imath/bp-groups-taxo/tree/beta-6

**Comment by valuser** [comment]
yes !   beta-6 is fixing the issue.


Thank you
Merci beaucoup!

**Comment by imath** [comment]
yw i'll merge it with master when 2.7 will be released.

imath.
http://profiles.wordpress.org/imath/
