### ISSUE TITLE
User Tags

### ISSUE THREAD

**Issue by thomastthai** [imath/bp-groups-taxo#20]
To leverage group tags even further, I recommend creating a complimentary plugin for user tags. During registration, there would be a box in a section called Interests (see my other issue post) for them to type in and select their interests. Those interest tags are pulled from the Group tags. Now we have relationships.

In their Profile page and in the Interests tab, give them the option to edit their interest tags.

When they visit the main Groups section, right after the "All Groups" and "My Groups" button have the "Recommended Groups" button. When they click on that, it would refresh the bottom portion and show all recommended groups for them to join. This should also have a widget too so it can be displayed on the sidebars in other pages.

Next, take a user's interests (via tags), subtract from those all the tags that already had groups attached, for each left over tag, find out how many other users have the same interests and sort them from most requested to least. This can serve as a list to recommend to the user to create groups for.

**Comment by thomastthai** [comment]
I found [a plugin](https://wordpress.org/plugins/user-tags/) that already handles the user tags. With a slight modification, it would compliment the User Tag plugin!

**Comment by imath** [comment]
No it's not this plugin territory and there are already member types.

imath.
http://profiles.wordpress.org/imath/

**Comment by thomastthai** [comment]
Isn't member types different than user tags?

**Comment by imath** [comment]
It's very similar. Anyway it's off topic here as this plugin is dealing with groups

imath.
http://profiles.wordpress.org/imath/
