### ISSUE TITLE
Limit 1 checkbox on group signup.

### ISSUE THREAD

**Issue by quinngoldwin** [imath/bp-groups-taxo#6]
I love this plugin iMath! I was wondering if there is any code I can add to restrict only 1 tag selection during group creation. I'm having users spam all the tags and selecting every option instead of groups that are relevant. I just would like them to only be able to select 1 checkbox. Any of your help would be greatly appreciated.

**Comment by imath** [comment]
You can use the 'bp_groups_taxo_tag_editor' filter to redefine the output so that it's using radio buttons. Or you can use javascript to transform the checkboxes behavior. Here's an example about this last possibility.

```php
function quinngoldwin_checkbox_as_radio() {
	if ( ! bp_is_group_create() && ! bp_is_group_admin_page() ) {
		return;
	}
	?>
	<script type="text/javascript">
	/* <![CDATA[ */
	( function( $ ) {
		$( '#buddypress input[name="_group_tags[]"]' ).click( function() {
			that = $( this );

			$( '#buddypress input[name="_group_tags[]"]:checked' ).each( function() {
				if ( $( this ).val() !== that.val() ) {
					$( this ).prop( 'checked', false );
				}
			} );
		} );
	} )(jQuery);
	/* ]]> */
	</script>
	<?php
}
add_action( 'wp_print_footer_scripts', 'quinngoldwin_checkbox_as_radio', 40 );
```
