### ISSUE TITLE
WP 4.4 (non-network) "You are not allowed to manage these items" error 

### ISSUE THREAD

**Issue by chasbeebe** [imath/bp-groups-taxo#7]
After test installing this plugin and attempting to add group tags as admin, I got a "You are not allowed to manage these items" error. Running WP 4.4/Buddypress 2.4.3. Based on this advice for a WooCommerce plugin: https://wordpress.org/support/topic/wp-44-you-are-not-allowed-to-manage-these-items?replies=10#post-7755373 , I changed 'show_ui' to 'true' in loader.php as a temporary fix, which does at least allow me to play with it for now.

**Comment by imath** [comment]
Thanks for your feedback, i'll look at it asap!!

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
oops wrong commit :(
